//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance_Vendor_Portal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class FINANCE_WEB_USERS
    {
        [DisplayName("User ID")]
        public int USERID { get; set; }
        [DisplayName("Vendor ID")]
        public string VENDOR_NUMBER { get; set; }
        [DisplayName("User Password")]
        public string USER_PASSWORD { get; set; }
        [DisplayName("Email Address")]
        public string EMAIL_ADDRESS { get; set; }
        [DisplayName("Admin User")]
        public Nullable<bool> ADMIN_USER { get; set; }
        [DisplayName("Password Expiry Date")]
        public Nullable<System.DateTime> OUT_DATE { get; set; }
    }
}
