//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class FINANCE_WEB_USERS
    {
        [Required(ErrorMessage = "Please provide your Vendor ID. ", AllowEmptyStrings = false)]
        public string VENDORNO { get; set; }

        [Required(ErrorMessage = "Please provide your Password. ", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string PASSWORD { get; set; }

        [Compare("PASSWORD", ErrorMessage = "Re-Password does not match. ")]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string REPASSWORD { get; set; }

        [RegularExpression(@"^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$", ErrorMessage = "Please provide valid email. ")]
        public string EMAILADDR { get; set; }

        public Nullable<bool> ADMINUSER { get; set; }

        public Nullable<System.DateTime> OUTDATE { get; set; }
    }
}
