CREATE TABLE [dbo].[WEBPORTAL] (
    [ABN]                  CHAR (11)     NULL,
    [SUPPLIER_DESCRIPTION] VARCHAR (120) NULL,
    [SUPPLIER_ACCOUNT]     VARCHAR (20)  NOT NULL,
    [REFERENCE]            VARCHAR (50)  NULL,
    [DOCUMENT_DATE]        DATETIME      NULL,
    [DOCUMENT_TYPE]        VARCHAR (50)  NULL,
    [NARRATION1]           VARCHAR (120) NULL,
    [NARRATION2]           VARCHAR (120) NULL,
    [NARRATION3]           VARCHAR (120) NULL,
    [STATUS]               CHAR (1)      NULL,
    [STAGE]                VARCHAR (50)  NULL,
    [APPROVAL_POOL]        VARCHAR (10)  NULL,
    [DUE_DATE]             DATETIME      NULL,
    [DOCUMENT_FILE_NAME]   CHAR (8)      NULL,
    PRIMARY KEY CLUSTERED ([SUPPLIER_ACCOUNT] ASC)
);