CREATE TABLE "SYSTEM"."WEBPORTAL" 
   (	"ABN" VARCHAR2(26 BYTE), 
	"SUPPLIER_DESCRIPTION" VARCHAR2(128 BYTE), 
	"SUPPLIER_ACCOUNT" VARCHAR2(26 BYTE), 
	"REFERENCE" VARCHAR2(26 BYTE), 
	"DOCUMENT_DATE" DATE, 
	"AMOUNT" VARCHAR2(26 BYTE), 
	"OUTSTANDING_AMOUNT" VARCHAR2(26 BYTE), 
	"ALLOCATED_AMOUNT" VARCHAR2(26 BYTE), 
	"DOCUMENT_TYPE" VARCHAR2(26 BYTE), 
	"NARRATION1" VARCHAR2(128 BYTE), 
	"NARRATION2" VARCHAR2(128 BYTE), 
	"NARRATION3" VARCHAR2(128 BYTE), 
	"STATUS" VARCHAR2(26 BYTE), 
	"STAGE" VARCHAR2(26 BYTE), 
	"APPROVAL_POOL" VARCHAR2(26 BYTE), 
	"DUE_DATE" DATE
   )