//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceVendorPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT
    {
        public string Code { get; set; }
        public string Area { get; set; }
        public string Contact1 { get; set; }
    }
}
