//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINANCE_WEB_USERS
    {
        private FINANCE_WEB_USERS newUser;
        private string p1;
        private string newEmail;
        private bool p2;
        private DateTime? nullable;

        public FINANCE_WEB_USERS() :base()
        {

        }

        public FINANCE_WEB_USERS(string inVendorNo, string inPassword, string inEmailAddr, bool inAdminuser, DateTime? inOutDate)
        {
            this.VENDORNO = inVendorNo;
            this.PASSWORD = inPassword;
            this.EMAILADDR = inEmailAddr;
            this.ADMINUSER = inAdminuser;
            this.OUTDATE = inOutDate;
        }

        public string VENDORNO { get; set; }
        public string PASSWORD { get; set; }
        public string EMAILADDR { get; set; }
        public bool ADMINUSER { get; set; }
        public Nullable<System.DateTime> OUTDATE { get; set; }
    }
}
