//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VendorPortalDatabaseEntities : DbContext
    {
        public VendorPortalDatabaseEntities()
            : base("name=VendorPortalDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CONTACT> CONTACTS { get; set; }
        public DbSet<FINANCE_WEB_USERS> FINANCE_WEB_USERS { get; set; }
        public DbSet<WEBPORTAL> WEBPORTALs { get; set; }
    }
}
