//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEBPORTAL
    {
        public string ABN { get; set; }
        public string SUPPLIER_DESCRIPTION { get; set; }
        public string SUPPLIER_ACCOUNT { get; set; }
        public string REFERENCE { get; set; }
        public Nullable<System.DateTime> DOCUMENT_DATE { get; set; }
        public string DOCUMENT_TYPE { get; set; }
        public string NARRATION1 { get; set; }
        public string NARRATION2 { get; set; }
        public string NARRATION3 { get; set; }
        public string STATUS { get; set; }
        public string STAGE { get; set; }
        public string APPROVAL_POOL { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public string DOCUMENT_FILE_NAME { get; set; }
    }
}
